Models/DB/Carro.cs
namespace mvc_crud.Models.DB
{
    public class Carro
    {
        public int Id { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public int AnoLancamento { get; set; }
        public int AnoMontagem { get; set; }
        public string Chassis { get; set; }
    }
}

Models/DB/Contato.cs
namespace mvc_crud.Models.DB
{
    public class Contato
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
    }
}

Models/DB/Produto.cs
namespace mvc_crud.Models.DB
{
    public class Produto
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public double Valor { get; set; }
        public int Estoque { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace mvc_crud.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CarroController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvc_crud.Data;
using mvc_crud.Models.DB;


namespace mvc_crud.Controllers
{
    public class CarroController : Controller
    {
        private readonly ILogger<CarroController> _logger;
        private readonly appContext _context;
        
        public CarroController(ILogger<CarroController> logger, appContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {   
            IList<Carro> carros = _context.Carros.ToList(); 
            return View(carros);
        }

        public IActionResult Novo()
        {
            return View();
        }

    [HttpPost]
        public IActionResult Novo([Bind("Id,Marca,Modelo,AnoLancamento,AnoMontagem,Chassis")]Carro novoCarro)
        {
            _context.Carros.Add(novoCarro);
            _context.SaveChanges();
            
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/ContatoController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvc_crud.Data;
using mvc_crud.Models.DB;


namespace mvc_crud.Controllers
{
    public class ContatoController : Controller
    {
        private readonly ILogger<ContatoController> _logger;
        private readonly appContext _context;
        
        public ContatoController(ILogger<ContatoController> logger, appContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {   
            IList<Contato> contatos = _context.Contatos.ToList(); 
            return View(contatos);
        }

        public IActionResult Novo()
        {
            return View();
        }

    [HttpPost]
        public IActionResult Novo([Bind("Id,Nome,Email,Telefone")]Contato novoContato)
        {
            _context.Contatos.Add(novoContato);
            _context.SaveChanges();
            
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvc_crud.Models;

namespace mvc_crud.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProdutoController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvc_crud.Data;
using mvc_crud.Models.DB;


namespace mvc_crud.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly ILogger<ProdutoController> _logger;
        private readonly appContext _context;
        
        public ProdutoController(ILogger<ProdutoController> logger, appContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {   
            IList<Produto> produtos = _context.Produtos.ToList(); 
            return View(produtos);
        }

        public IActionResult Novo()
        {
            return View();
        }

    [HttpPost]
        public IActionResult Novo([Bind("Id,Nome,Valor,Estoque")]Produto novoProduto)
        {
            _context.Produtos.Add(novoProduto);
            _context.SaveChanges();
            
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Carro/Index.cshtml
@model IList<mvc_crud.Models.DB.Carro>

@{
    ViewData["Title"] = "Carros";
}

<a asp-action="Novo">Carro novo</a>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Marca</th>
            <th>Modelo</th>
            <th>AnoLancamento</th>
            <th>AnoMontagem</th>
            <th>Chassis</th>
        </tr>
    </thead>
    <tbody>
@foreach (mvc_crud.Models.DB.Carro carro in Model)
{
      <tr>
            <td>@Html.DisplayFor(modelCarro => carro.Id)</td>
              <td>@Html.DisplayFor(modelCarro => carro.Marca)</td>
                <td>@Html.DisplayFor(modelCarro => carro.Modelo)</td>
                  <td>@Html.DisplayFor(modelCarro => carro.AnoLancamento)</td>
                    <td>@Html.DisplayFor(modelCarro => carro.AnoMontagem)</td>
                      <td>@Html.DisplayFor(modelCarro => carro.Chassis)</td>

       
        </tr>   
}
   
    </tbody>
</table>

Views/Carro/Novo.cshtml
@model mvc_crud.Models.DB.Carro

@{
    ViewData["Title"] = "Novo Carro";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Novo">
                <div class="form-group">
                <label asp-for="Marca" class="control-label">Marca</label>
                <input asp-for="Marca" class="form-control" type="text" />
                </div>
                <div class="form-group">
                <label asp-for="Modelo" class="control-label">Modelo</label>
                <input asp-for="Modelo" class="form-control" type="text" />
                </div>
                <div class="form-group">
                <label asp-for="AnoLancamento" class="control-label">AnoLancamento</label>
                <input asp-for="AnoLancamento" class="form-control" type="text" />
                </div>
                <div class="form-group">
                <label asp-for="AnoMontagem" class="control-label">AnoMontagem</label>
                <input asp-for="AnoMontagem" class="form-control" type="text" />
                </div>
                <div class="form-group">
                <label asp-for="Chassis" class="control-label">Chassis</label>
                <input asp-for="Chassis" class="form-control" type="text" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Criar" class="btn btn-primary">
                </div>                
        </form>
    </div>
</div>

Views/Contato/Index.cshtml
@model IList<mvc_crud.Models.DB.Contato>

@{
    ViewData["Title"] = "Contatos";
}

<a asp-action="Novo">Contato novo</a>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Email</th>
            <th>Telefone</th>
        </tr>
    </thead>
    <tbody>
@foreach (mvc_crud.Models.DB.Contato contato in Model)
{
      <tr>
            <td>@Html.DisplayFor(modelContato => contato.Id)</td>
              <td>@Html.DisplayFor(modelContato => contato.Nome)</td>
                <td>@Html.DisplayFor(modelContato => contato.Email)</td>
                  <td>@Html.DisplayFor(modelContato => contato.Telefone)</td>       
        </tr>   
}
   
    </tbody>
</table>

Views/Contato/Novo.cshtml
@model mvc_crud.Models.DB.Contato

@{
    ViewData["Title"] = "Novo Contato";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Novo">
                <div class="form-group">
                <label asp-for="Nome" class="control-label">Nome</label>
                <input asp-for="Nome" class="form-control" type="text" />
                </div>
                <div class="form-group">
                <label asp-for="Email" class="control-label">Email</label>
                <input asp-for="Email" class="form-control" type="text" />
                </div>
                <div class="form-group">
                <label asp-for="Telefone" class="control-label">Telefone</label>
                <input asp-for="Telefone" class="form-control" type="text" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Criar" class="btn btn-primary">
                </div>                
        </form>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Produto/Index.cshtml
@model IList<mvc_crud.Models.DB.Produto>

@{
    ViewData["Title"] = "Produtos";
}

<a asp-action="Novo">Produto novo</a>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Valor</th>
            <th>Estoque</th>
        </tr>
    </thead>
    <tbody>
@foreach (mvc_crud.Models.DB.Produto produto in Model)
{
      <tr>
            <td>@Html.DisplayFor(modelProduto => produto.Id)</td>
              <td>@Html.DisplayFor(modelProduto => produto.Nome)</td>
                <td>@Html.DisplayFor(modelProduto => produto.Valor)</td>
                  <td>@Html.DisplayFor(modelProduto => produto.Estoque)</td>       
        </tr>   
}
   
    </tbody>
</table>

Views/Produto/Novo.cshtml
@model mvc_crud.Models.DB.Produto

@{
    ViewData["Title"] = "Novo Produto";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Novo">
                <div class="form-group">
                <label asp-for="Nome" class="control-label">Nome</label>
                <input asp-for="Nome" class="form-control" type="text" />
                </div>
                <div class="form-group">
                <label asp-for="Valor" class="control-label">Valor</label>
                <input asp-for="Valor" class="form-control" type="text" />
                </div>
                <div class="form-group">
                <label asp-for="Estoque" class="control-label">Estoque</label>
                <input asp-for="Estoque" class="form-control" type="text" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Criar" class="btn btn-primary">
                </div>                
        </form>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc_crud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvc_crud</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Carro" asp-action="Index">Carros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - mvc_crud - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>